-- auto Generated on 2020-07-01 21:10:41 
-- DROP TABLE IF EXISTS `user`; 
CREATE TABLE `user`(
    `id` BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
    `create_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'createTime',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `user_name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'userName',
    `real_name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'realName',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '`user`';
